services:
  critik-v_db:
    image: postgres:latest
    container_name: critik-v-db

    env_file: ../server/.env
    environment:
      # POSTGRES_USER: admin
      # POSTGRES_PASSWORD: password
      # POSTGRES_DB: DB
      # POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_critik_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d DB"]
      interval: 5s
      timeout: 5s
      retries: 5

# networking configuration
volumes:
  db_critik_data:
    driver: local
